target: run_source1 run_source2 run_source3 run_router run_destination

run_router:
	python router.py
run_destination:
	python destination.py
run_source1:
	python source.py 0
run_source2:
	python source.py 1
run_source3:
	python source.py 2
